server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/skillsprintlite
    username: skillsprint
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  redis:
    host: localhost
    port: 6379

api:
  keys:
    allowed: my-secure-key-1,my-secure-key-2